#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_DIR="/home/artur/projects/agents-space/legacy-todo"
REPO_SLUG="Art4/legacy-todo"
CONFIG_DIR="$HOME/.config/gh-app"
mkdir -p "$CONFIG_DIR"
ENV_FILE="$CONFIG_DIR/legacy-todo-refactor-bot.env"

banner "GitHub App: refactor-bot for legacy-todo"

say "This sets up a separate GitHub identity for the continuous-refactoring"
say "skills to act under — not your personal account. It shows up in the UI"
say "as its own <app-name>[bot] user on issues, comments and PRs."
say ""
note "No new GitHub account/email needed, no change to your personal 'gh auth"
note "login', and the private key never lands inside the repo."

# ── Stage 1: register the App ──────────────────────────────────────────────
stage "Register the GitHub App"
say "We'll create a GitHub App under your existing account. It only acts on"
say "this one repo once installed — nothing else on your account changes."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: try 'legacy-todo-refactor-bot' (must be globally unique"
step "  on GitHub — if it's taken, add a suffix, e.g. 'legacy-todo-refactor-bot-art4')."
step "Homepage URL: https://github.com/${REPO_SLUG}"
step "Webhook: uncheck 'Active' (this bot doesn't need webhooks)."
step "Repository permissions:"
step "  - Contents: Read and write"
step "  - Issues: Read and write"
step "  - Pull requests: Read and write"
step "'Where can this GitHub App be installed?': Only on this account."
step "Click 'Create GitHub App' at the bottom."
say ""
say "You land on the app's settings page. Near the top, under 'About', find"
say "the numeric 'App ID' (NOT the 'Client ID', which looks like Iv1.xxxx)."
ask APP_NAME "Which name did you register the app under?"
ask APP_ID "Paste the App ID (number):"
write_env APP_NAME "$APP_NAME"
write_env APP_ID "$APP_ID"

# ── Stage 2: generate and store the private key ────────────────────────────
stage "Generate the private key"
say "Still on the app's settings page (General tab)."
step "Scroll down to 'Private keys' → click 'Generate a private key'."
step "A .pem file downloads automatically (usually into ~/Downloads)."
say ""
say "We'll move it out of Downloads into a fixed, non-repo location with"
say "restrictive permissions, so it's never at risk of being committed."
ask DOWNLOADED_PEM "Paste the full path to the downloaded .pem file:"

PEM_PATH="$CONFIG_DIR/legacy-todo-refactor-bot.pem"
if [[ "$DOWNLOADED_PEM" == "$PEM_PATH" ]]; then
  note "already at the target location"
elif [[ -f "$DOWNLOADED_PEM" ]]; then
  mv "$DOWNLOADED_PEM" "$PEM_PATH"
  printf '  %s✓ moved%s %s → %s\n' "$GREEN" "$RESET" "$DOWNLOADED_PEM" "$PEM_PATH"
else
  warn "couldn't find a file at $DOWNLOADED_PEM"
  warn "move it yourself to $PEM_PATH"
  SKIPPED+=("move the downloaded .pem to $PEM_PATH")
fi
chmod 600 "$PEM_PATH" 2>/dev/null || true
write_env PEM_PATH "$PEM_PATH"

# ── Stage 3: install the App on this repo only ─────────────────────────────
stage "Install the App on legacy-todo"
say "Back on the app's settings page, left sidebar."
step "Click 'Install App'."
step "Pick your account."
step "Choose 'Only select repositories' → select '${REPO_SLUG}' → click Install."
say ""
say "After installing, the URL looks like:"
say "  https://github.com/settings/installations/12345678"
say "The trailing number is the Installation ID."
ask INSTALLATION_ID "Paste the Installation ID:"
write_env INSTALLATION_ID "$INSTALLATION_ID"

# ── Stage 4: verify ─────────────────────────────────────────────────────────
stage "Verify the bot works"
WRAPPER="$REPO_DIR/scripts/bot-gh-refactor.sh"
say "This calls scripts/bot-gh-refactor.sh, which mints a fresh 1h token from"
say "the private key and makes one read-only API call as the bot — nothing is"
say "created or changed on GitHub."
if [[ -x "$WRAPPER" ]]; then
  if confirm "Run the verification call now?"; then
    if OUTPUT=$("$WRAPPER" api "repos/${REPO_SLUG}" --jq '.full_name' 2>&1); then
      printf '  %s✓ authenticated as the bot%s — repo full_name = %s\n' "$GREEN" "$RESET" "$OUTPUT"
    else
      warn "verification call failed:"
      note "$OUTPUT"
      SKIPPED+=("verify manually: $WRAPPER api repos/${REPO_SLUG}")
    fi
  else
    SKIPPED+=("run $WRAPPER api repos/${REPO_SLUG} to verify later")
  fi
else
  warn "$WRAPPER not found or not executable"
  SKIPPED+=("chmod +x $WRAPPER, then run: $WRAPPER api repos/${REPO_SLUG}")
fi

note ""
note "From now on, use ./scripts/bot-gh-refactor.sh <gh args...> instead of"
note "plain 'gh' for anything the refactor-bot should do (issues, PRs, ...)."
note "Your own 'gh auth login' is untouched, and stays your personal account"
note "everywhere else, including in this repo when you run plain 'gh'."
# ──────────────────────────────────────────────────────────────────────────

finish
